version: "3"

services:
  worker:
    build: ./worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./worker/worker.py:/app/worker.py
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: ./app
    volumes:
      - ./worker/worker.py:/app/worker.py
    ports:
      - 5050:5050
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - worker
  job_viewer:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - redis